### ISSUE TITLE
NullPointerException when launching Kotlin QTConsole (if jupyter is not a available in the PATH)

### ISSUE THREAD

**Issue by jhhcs** [GhidraJupyter/ghidra-jupyter-kotlin#53]
I followed the manual installation steps. When attempting to launch the Kotlin QTConsole via the button in the code browser, a `NullPointerException` with the following stack trace is shown:
```
Cannot invoke "java.io.File.toPath()" because the return value of "java.io.File.getParentFile()" is null
java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because the return value of "java.io.File.getParentFile()" is null
	at GhidraJupyterKotlin.ConnectionFile.writeConfigFile(ConnectionFile.java:96)
	at GhidraJupyterKotlin.ConnectionFile.create(ConnectionFile.java:20)
	at GhidraJupyterKotlin.JupyterKotlinPlugin$1.actionPerformed(JupyterKotlinPlugin.java:87)
	at docking.DockingActionProxy.actionPerformed(DockingActionProxy.java:47)
	at docking.DockingActionPerformer.lambda$perform$0(DockingActionPerformer.java:73)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2024-Nov-05 1643 EST
Ghidra Version: 11.2.1
Java Home: C:\Program Files\OpenJDK\jdk-22.0.2
JVM Version: Oracle Corporation 22.0.2
OS: Windows 10 10.0 amd64
Workstation: [REDACTED]
```
This luckily includes my OS and Ghidra version info. Cheers!

**Comment by jhhcs** [comment]
PS: I used release [v1.6.13](https://github.com/GhidraJupyter/ghidra-jupyter-kotlin/releases/tag/v1.6.13).

**Comment by fmagin** [comment]
This specific problem happens when the plugin fails at running the `jupyter --runtime-dir` command, because `jupyter` isn't in the `PATH` that Ghidra uses when spawning subprocesses. This happens when `jupyter` is only installed in a virtualenv and Ghidra wasn't started from within that virtualenv.

The new `v1.6.14` release has somewhat clearer errors for this, but the correct fix in the future will be that the user can configure the virtual env for the jupyter tooling from within the UI
